apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
  name: user
spec:
  ports:
  - port: 8811
    protocol: TCP
    targetPort: 8811
  selector:
    app: user
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: 192.168.2.169/demo/user:latest
        ports:
        - containerPort: 8811

